package fbatms;

import db.MyConnection;
import java.awt.Desktop;
import java.net.URL;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class Home extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu1
     */
    Color defaultColor = new Color(1, 82, 173);
    Color hoverColor = new Color(0, 145, 122);
    int xx, xy;

    public Home() {
        initComponents();
        setImage();
        setNumber();
    }

    private void setImage() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/banner.png"));
        Image img = icon.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        jLabelImage.setIcon(new ImageIcon(img));
    }

    private void setNumber() {
        txtCustomers.setText(String.valueOf(totalCustomers()));
        txtSuppliers.setText(String.valueOf(totalSuppliers()));
        txtItems.setText(String.valueOf(totalItems()));
        txtCustomersOrders.setText(String.valueOf(totalCustomersOrders()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnManageStudents1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCustomers = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtSuppliers = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtItems = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtCustomersOrders = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnManageStudents3 = new javax.swing.JButton();
        btnManageStudents5 = new javax.swing.JButton();
        btnManageStudents6 = new javax.swing.JButton();
        btnManageStudents7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 450));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 1, 47));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 125, 245), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 125, 245), 4, true));

        btnLogout.setBackground(new java.awt.Color(223, 0, 226));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        btnManageStudents1.setBackground(new java.awt.Color(136, 125, 245));
        btnManageStudents1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnManageStudents1.setText("Manage Staff");
        btnManageStudents1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStudents1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStudents1MouseExited(evt);
            }
        });
        btnManageStudents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageStudents1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageStudents1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 730));

        jPanel2.setBackground(new java.awt.Color(136, 125, 245));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 70, 107), 4, true));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fingerprint Based ATM System - FBATMS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 7, 610, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 910, 60));

        jLabelImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 610, 370));

        jPanel6.setBackground(new java.awt.Color(136, 125, 245));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customers.png")));

        txtCustomers.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCustomers.setText("2");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Customers");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCustomers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 200, 90));

        jPanel8.setBackground(new java.awt.Color(136, 125, 245));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accounts.png")));

        txtSuppliers.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtSuppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSuppliers.setText("560");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Accounts");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSuppliers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(20, 20, 20))
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 200, 90));

        jPanel9.setBackground(new java.awt.Color(136, 125, 245));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/staff.png")));

        txtItems.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtItems.setText("30");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Staff");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 200, 90));

        jPanel5.setBackground(new java.awt.Color(136, 125, 245));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transactions.png")));

        txtCustomersOrders.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtCustomersOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCustomersOrders.setText("50");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Transactions");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomersOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCustomersOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 200, 90));

        btnManageStudents3.setBackground(new java.awt.Color(244, 143, 67));
        btnManageStudents3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnManageStudents3.setText("Suppliers Orders");
        btnManageStudents3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStudents3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStudents3MouseExited(evt);
            }
        });
        btnManageStudents3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents3ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageStudents3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnManageStudents5.setBackground(new java.awt.Color(244, 143, 67));
        btnManageStudents5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnManageStudents5.setText("Manage Staff");
        btnManageStudents5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStudents5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStudents5MouseExited(evt);
            }
        });
        btnManageStudents5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents5ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageStudents5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnManageStudents6.setBackground(new java.awt.Color(136, 125, 245));
        btnManageStudents6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnManageStudents6.setText("Transactions Report");
        btnManageStudents6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStudents6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStudents6MouseExited(evt);
            }
        });
        btnManageStudents6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents6ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageStudents6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, 250, 90));

        btnManageStudents7.setBackground(new java.awt.Color(136, 125, 245));
        btnManageStudents7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnManageStudents7.setText("Customers Report");
        btnManageStudents7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStudents7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStudents7MouseExited(evt);
            }
        });
        btnManageStudents7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents7ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageStudents7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 250, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Are You Sure To Logout Now?", "Logout", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnManageStudents1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents1MouseEntered

    private void btnManageStudents1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents1MouseExited

    private void btnManageStudents1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents1ButtonActionPerformed


try{
            
          Desktop.getDesktop().browse(new URL("http://localhost/FBATMS/Manage_Staff").toURI());  
            
            
        }
        catch(Exception e)
        {}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents1ButtonActionPerformed

    private void btnManageStudents3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents3MouseEntered

    private void btnManageStudents3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents3MouseExited

    private void btnManageStudents3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents3ButtonActionPerformed

    private void btnManageStudents5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents5MouseEntered

    private void btnManageStudents5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents5MouseExited

    private void btnManageStudents5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents5ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents5ButtonActionPerformed

    private void btnManageStudents7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents7MouseEntered

    private void btnManageStudents7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents7MouseExited

    private void btnManageStudents7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents7ButtonActionPerformed

try{
            
          Desktop.getDesktop().browse(new URL("http://localhost/FBATMS/Customers_Report").toURI());  
            
            
        }
        catch(Exception e)
        {}


    }//GEN-LAST:event_btnManageStudents7ButtonActionPerformed

    private void btnManageStudents6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents6ButtonActionPerformed

        try{

            Desktop.getDesktop().browse(new URL("http://localhost/FBATMS/Transactions_Report").toURI());

        }
        catch(Exception e)
        {}

    }//GEN-LAST:event_btnManageStudents6ButtonActionPerformed

    private void btnManageStudents6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents6MouseExited

    private void btnManageStudents6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStudents6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudents6MouseEntered

    //get the total number of customers
    public int totalCustomers() {
        int total = 0;
        Connection con = MyConnection.getConnection();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) AS 'total' FROM customers");
            while (rs.next()) {
                total = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;

    }

    //get the total number of accounts
    public int totalSuppliers() {
        int total = 0;
        Connection con = MyConnection.getConnection();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) AS 'total' FROM accounts");
            while (rs.next()) {
                total = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }

    //get the total number of staff
    public int totalItems() {
        int total = 0;
        Connection con = MyConnection.getConnection();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) AS 'total' FROM staff");
            while (rs.next()) {
                total = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }

    //get the total number of transactions
    public int totalCustomersOrders() {
        int total = 0;
        Connection con = MyConnection.getConnection();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) AS 'total' FROM transactions");
            while (rs.next()) {
                total = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageStudents1;
    private javax.swing.JButton btnManageStudents3;
    private javax.swing.JButton btnManageStudents5;
    private javax.swing.JButton btnManageStudents6;
    private javax.swing.JButton btnManageStudents7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txtCustomers;
    private javax.swing.JLabel txtCustomersOrders;
    private javax.swing.JLabel txtItems;
    private javax.swing.JLabel txtSuppliers;
    // End of variables declaration//GEN-END:variables

    private static class stud extends Component {

        public stud() {
        }
    }
}
